name: First workflow

on: workflow_dispatch # executar manualmente

jobs:
  first-job: # pode ser qualquer nome
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done - bye!"
